### ISSUE TITLE
Close activity from outside

### ISSUE THREAD

**Issue by WilliamBrain** [hzw1199/AwesomeWebView-Android#5]
I want to close the webview activity from outside.
Main usecase:
I want to open the web view for oAuth authentication.
When authentication is finished, I want to close the web view automatically.
My plan was to use the WebViewListener and overwrite onPageFinished.
When a specific URL is finished, I know I can close the web view.
My problem is: I can't find a nice way to close the activity because I have no object reference to it.
Is there a way I overlooked?

**Comment by sukhcha-in** [comment]
@hzw1199 please look into this

**Comment by hzw1199** [comment]
> I want to close the webview activity from outside.
> Main usecase:
> I want to open the web view for oAuth authentication.
> When authentication is finished, I want to close the web view automatically.
> My plan was to use the WebViewListener and overwrite onPageFinished.
> When a specific URL is finished, I know I can close the web view.
> My problem is: I can't find a nice way to close the activity because I have no object reference to it.
> Is there a way I overlooked?



> @hzw1199 please look into this

@WilliamBrain @sukhcha-in 
Let me show you how to make it.

1. Create OauthActivity extending `AwesomeWebViewActivity.`

2. In OauthActivity, create your own `WebViewClient` extending `AwesomeWebViewActivity.MyWebViewClient` and override `onPageFinished` to listen to the specific URL finished. When specific URL finished, call `finish()`.

3. Override `protected WebViewClient buildWebViewClient()` method in OauthActivity and return the instance of your own `WebViewClient`.

4. Create your Builder extending `AwesomeWebView.Builder` in OauthActivity:
```java
public static class Builder extends AwesomeWebView.Builder{

    public Builder(@NonNull Activity activity) {
        super(activity);
    }

    public Builder(@NonNull Context context) {
        super(context);
    }

    @Override
    public void load(String data) {
        this.load(data, "text/html", "UTF-8");
    }

    @Override
    public void load(String data, String mimeType, String encoding) {
        this.mimeType = mimeType;
        this.encoding = encoding;
        this.show((String)null, data);
    }

    @Override
    public void show(@NonNull String url) {
        this.show(url, (String)null);
    }

    @Override
    public void show(String url, String data) {
        this.url = url;
        this.data = data;
        this.key = System.identityHashCode(this);

        if (!listeners.isEmpty()) new BroadCastManager(context, key, listeners);

        Intent intent = new Intent(context, OauthActivity.class);
        intent.putExtra("builder", this);

        Ctx.startActivity(intent);

        if (context instanceof Activity) {
            ((Activity) context).overridePendingTransition(animationOpenEnter, animationOpenExit);
        }
    }
}
```

5. Call 
```java
new OauthActivity.Builder(context);
```
 to open OauthActivity
